### ISSUE TITLE
INFOGRAFIA

### ISSUE THREAD

**Issue by JORGELUIS2266** [SistemasTecTlaxiaco/infografia-de-hilos-JORGELUIS2266#2]
[JORGE LUIS HERNANDEZ MATRA -INFOGRAFIA.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-JORGELUIS2266/files/15099015/JORGE.LUIS.HERNANDEZ.MATRA.-INFOGRAFIA.pdf)

**Comment by IrvinSanchez-dev** [comment]
Dado a la rubrica de evaluación, obtuviste un 20%

*Si cumple con todo lo señalado

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
